# Generated by Django 5.2.17 on 2026-09-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='✦', max_length=8)),
                ('theme_class', models.SlugField(default='elementary')),
                ('chapter', models.CharField(max_length=100)),
                ('lead', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'kategorie',
                'verbose_name_plural': 'kategorie',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='school.category')),
            ],
            options={
                'verbose_name': 'aktualita',
                'verbose_name_plural': 'aktuality',
                'ordering': ['-published_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('category', 'slug'), name='unique_news_slug_per_category')],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='school.category')),
            ],
            options={
                'verbose_name': 'subkategorie',
                'verbose_name_plural': 'subkategorie',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'slug'), name='unique_subcategory_slug_per_category')],
            },
        ),
    ]
